//Email encryption
// Encryption generated by https://rumkin.com/tools/mailto_encoder
ML = '.nehicam@goprl8';
MI = '<' + '6;362=;412=>89764=05:7';
OT = '';
for (j = 0; j < MI.length; j++) {
  OT += ML.charAt(MI.charCodeAt(j) - 48);
}
document.getElementById('encrypt2').innerHTML = OT;
document.getElementById('encrypt1').href = 'mailto:' + OT;

//Script to solve error:
// jquery-min.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

jQuery.event.special.touchstart = {
  setup: function(_, ns, handle) {
    if (ns.includes('noPreventDefault')) {
      this.addEventListener('touchstart', handle, { passive: false });
    } else {
      this.addEventListener('touchstart', handle, { passive: true });
    }
  }
};

/* ==========================================================================
   Page Loader
   ========================================================================== */
$(window).load(function() {
  'use strict';
  $('#loader').fadeOut();
});

/* ==========================================================================
   CounterUp
   ========================================================================== */
jQuery(document).ready(function($) {
  $('.counter').counterUp({
    delay: 1,
    time: 500
  });
});

/* slicknav mobile menu active  */
$('.mobile-menu').slicknav({
  prependTo: '.navbar-header',
  parentTag: 'liner',
  allowParentLinks: true,
  duplicate: true,
  label: '',
  closedSymbol: '<i class="icon-arrow-right"></i>',
  openedSymbol: '<i class="icon-arrow-down"></i>'
});

/* ==========================================================================
   MixitUp
   ========================================================================== */
$(function() {
  $('#portfolio').mixItUp();
});

/* ==========================================================================
   Carousel Main Slider
   ========================================================================== */
$('.carousel-slider').owlCarousel({
  navigation: true,
  pagination: false,
  slideSpeed: 1000,
  stopOnHover: true,
  autoPlay: true,
  items: 1,
  itemsDesktop: [1199, 1],
  itemsDesktopSmall: [980, 1],
  itemsTablet: [768, 1],
  itemsTablet: [767, 1],
  itemsTabletSmall: [480, 1],
  itemsMobile: [479, 1]
});

/* ==========================================================================
   Touch Owl Carousel
   ========================================================================== */
$('.touch-slider').owlCarousel({
  navigation: true,
  pagination: false,
  slideSpeed: 1000,
  stopOnHover: true,
  autoPlay: true,
  items: 1,
  itemsDesktop: [1199, 1],
  itemsDesktopSmall: [980, 1],
  itemsTablet: [768, 1],
  itemsTablet: [767, 1],
  itemsTabletSmall: [480, 1],
  itemsMobile: [479, 1]
});

$('.touch-slider')
  .find('.owl-prev')
  .html('<i class="icon-arrow-left"></i>');
$('.touch-slider')
  .find('.owl-next')
  .html('<i class="icon-arrow-right"></i>');

$('.carousel-slider')
  .find('.owl-prev')
  .html('<i class="icon-arrow-left"></i>');
$('.carousel-slider')
  .find('.owl-next')
  .html('<i class="icon-arrow-right"></i>');

// $(window).on('scroll', function() {
//     if ($(window).scrollTop() > 20) {
//         $('.header-top-area').addClass('menu-bg');
//     } else {
//         $('.header-top-area').removeClass('menu-bg');
//     }
// });

/* ==========================================================================
   Back Top Link
   ========================================================================== */
var offset = 200;
var duration = 500;
$(window).scroll(function() {
  if ($(this).scrollTop() > offset) {
    $('.back-to-top').fadeIn(400);
  } else {
    $('.back-to-top').fadeOut(400);
  }
});
$('.back-to-top').click(function(event) {
  event.preventDefault();
  $('html, body').animate(
    {
      scrollTop: 0
    },
    600
  );
  return false;
});

jQuery(function($) {
  //Initiat WOW JS
  new WOW().init();

  // one page navigation
  $('.main-navigation').onePageNav({
    currentClass: 'active'
  });
});

jQuery(document).ready(function() {
  $('body').scrollspy({
    target: '.navbar-collapse',
    offset: 195
  });

  $(window).on('scroll', function() {
    if ($(window).scrollTop() > 80) {
      $('.fixed-top').addClass('menu-bg');
    } else {
      $('.fixed-top').removeClass('menu-bg');
    }
  });
});
